### ISSUE TITLE
Refactor OutsideEPG??

### ISSUE THREAD

**Issue by kecorbin** [datacenter/acitoolkit#104]
OutsideEPG should probably be refactored, this is a bit confusing as this class actually represents the l3extOut class, while OutsideNetwork represents the external EPG (l3extInstP)

Thoughts?

**Comment by michsmit99** [comment]
I tend to agree. However, this would not be backwards compatible. Are there folks using OutsideEPG where changing this would be a problem ?

**Comment by michsmit99** [comment]
I refactored the OutsideEPG code to be the following classes:
OutsideL3 (roughly l3extOut)
OutsideEPG (roughly l3extInstP)
OutsideNetwork (roughly l3extSubnet)

Since this change is not backward compatible, I also updated the version to v0.3
