### ISSUE TITLE
Error retrieving EPG attributes (bridge domain)

### ISSUE THREAD

**Issue by irr** [datacenter/acitoolkit#114]
I run into this issue under python2.7 with ACI==1.1(1o) and acitoolkit==0.3.1.

1) sample code (bug-test.py):

from acitoolkit.acitoolkit import *
import requests, requests.packages

requests.packages.urllib3.disable_warnings()

APIC_USER = '...'
APIC_PWD = '...'

LOG_LEVEL = logging.INFO
LOG_FORMAT = '[%(levelname)1.1s %(asctime)s %(module)s:%(lineno)d] %(message)s'

logging.basicConfig(format=LOG_FORMAT)
logging.getLogger().setLevel(LOG_LEVEL)

session = Session("https://apic", APIC_USER, APIC_PWD)
session.login()

tenant = Tenant("bug_tenant")
tenant.mark_as_deleted()
print session.push_to_apic(tenant.get_url(), data=tenant.get_json())

tenant = Tenant("bug_tenant")
context = Context("bug_context", tenant)

bd = BridgeDomain("bug_bridge_domain", tenant)
bd.add_context(context)
subnet = Subnet("bug_subnet", bd)
subnet.set_addr("192.168.0.1/24")

app = AppProfile("bug_appprofile", tenant)
epg = EPG("bug_epg", app)
epg.add_bd(bd)

hasbd = epg.has_bd()
getbd = epg.get_bd()
print "\t\t", "OK: epg.has_bd=%s and epg.get_bd=%s" % (hasbd, getbd)

print session.push_to_apic(tenant.get_url(), data=tenant.get_json())

tenants_list = Tenant.get(session)
for t in tenants_list:
    if t.name == "bug_tenant":
        print t.name
        bd = BridgeDomain.get(session, t)[0]
        print "\t", bd.name
        app = AppProfile.get(session, t)[0]
        print "\t", app
        epg = EPG.get(session, app, t)[0]
        print "\t", epg
        hasbd = epg.has_bd()
        getbd = epg.get_bd()
        print "\t\t", "BUG: epg.has_bd=%s and epg.get_bd=%s" % (hasbd, getbd)

2) Problem:

$ python bug-test.py 
[I 2015-08-11 10:52:07,370 acisession:408] Initializing connection to the APIC
[I 2015-08-11 10:52:07,377 connectionpool:735] Starting new HTTPS connection (1): apic
<Response [200]>
OK: epg.has_bd=True and epg.get_bd=bug_bridge_domain
<Response [200]>
bug_tenant
bug_bridge_domain
bug_appprofile
bug_epg
BUG: epg.has_bd=False and epg.get_bd=None

3) Summary:

When I use epg.add_bd and after that use epg.has_bd and epg.get_bd everything seems fine. When I query the tenant's list (tenants_list = Tenant.get(session)) and after that I try to inspect the already created tenant/epg with:
        epg = EPG.get(session, app, t)[0]
        hasbd = epg.has_bd()  <--- returning False
        getbd = epg.get_bd() <--- returning None

What am I doing wrong?

Thanks in advance,
 
    Ivan

**Comment by dnq** [comment]
Hi Ivan,

Great bug file, made it really easy to reproduce the bug :-)

I think the issue is related to two things, first you have to use the .get_deep() function instead of the .get function for the Tenant itself, like this:
t = Tenant.get_deep(session, names=('bug_tenant',))[0]

After that you can grab the required EPG directly from the Tenant:
epg_name = 'bug_epg'
epg_search = Search()
epg_search.name = epg_name
epg = app.find(epg_search)[0]

If i do it this way, i get the desired output:
```
epg.has_bd()
True
epg.get_bd()
<acitoolkit.acitoolkit.BridgeDomain object at 0x10bfd79d0>
```

If you use a plain '.get' then there is no resolution of all the relationships, this is provided by '.get_deep' and internal by '._extract_relationships' which is called by '.get_deep'.

Hope this helps.
Cheers
Richy

**Comment by dnq** [comment]
Btw this is my working example:
```
#!/usr/bin/env python
from acitoolkit.acitoolkit import *
import requests, requests.packages

requests.packages.urllib3.disable_warnings()

APIC_USER = '...'
APIC_PWD = '...'

LOG_LEVEL = logging.INFO
LOG_FORMAT = '[%(levelname)1.1s %(asctime)s %(module)s:%(lineno)d] %(message)s'

logging.basicConfig(format=LOG_FORMAT)
logging.getLogger().setLevel(LOG_LEVEL)

session = Session("https://apic", APIC_USER, APIC_PWD)
session.login()

t = Tenant.get_deep(session, names=('bug_tenant',))[0]

epg_name = 'bug_epg'
epg_search = Search()
epg_search.name = epg_name
epg = t.find(epg_search)[0]

print(epg.has_bd())
print(epg.get_bd())
```

**Comment by irr** [comment]
Hi Richy, 

"If you use a plain '.get' then there is no resolution of all the relationships, this is provided by '.get_deep' and internal by '._extract_relationships' which is called by '.get_deep'."

Thanks for you great help and explanation.

Best regards,
   Ivan
