### ISSUE TITLE
Endpointtracker  - inconsistent database naming

### ISSUE THREAD

**Issue by hrtspgdms** [datacenter/acitoolkit#130]
Hi,
Trying to run some of the applications with no success I have found that while endpoint-tracker.py creates the database 'endpointtracker' other modules like endpoint-tracker-gui.py or acitoolkitvisualizationslib.py are expecting 'acitoolkit'

Thanks,
Alonso

**Comment by michsmit99** [comment]
Just checked in a fix for the database name in the GUI and visualizations. (commit f3c3590232b31c72844d53f2fe38fc64a90d9292)
