### ISSUE TITLE
set_dom_deployment_immediacy and set_dom_resolution_immediacy fail

### ISSUE THREAD

**Issue by andraesincostan** [datacenter/acitoolkit#142]
Hi 
My script fails to change the immediacy for the domain.
Here my script:

    dom = ACI.EPGDomain.get_by_name(session, 'phys')
    t = ACI.Tenant('tktest')
    app = ACI.AppProfile('app1', t)
    epg = ACI.EPG('epg1', app)
    epg.add_infradomain(dom)
    epg.set_dom_deployment_immediacy('immediate')
    epg.set_dom_resolution_immediacy('immediate')
    session.push_to_apic(t.get_url(), t.get_json())

The script exists with keyError: **fvRsDomAtt**

    Traceback (most recent call last): File "create-complete-egp.py", line 85, in resp = tenant.push_to_apic(session) File "/home/ubuntu-user/AciToolKit/acitoolkit/acitoolkit/acitoolkit.py", line 132, in push_to_apic self.get_json()) File "/home/ubuntu-user/AciToolKit/acitoolkit/acitoolkit/acitoolkit.py", line 121, in get_json attributes=attr) File "/home/ubuntu-user/AciToolKit/acitoolkit/acitoolkit/acibaseobject.py", line 900, in get_json data = child.get_json() File "/home/ubuntu-user/AciToolKit/acitoolkit/acitoolkit/acitoolkit.py", line 330, in get_json attributes=attr) File "/home/ubuntu-user/AciToolKit/acitoolkit/acitoolkit/acibaseobject.py", line 900, in get_json data = child.get_json() File "/home/ubuntu-user/AciToolKit/acitoolkit/acitoolkit/acitoolkit.py", line 998, in get_json text['fvRsDomAtt']['attributes']['instrImedcy'] = self._dom_deployment_immediacy KeyError: 'fvRsDomAtt'

If I comment the lines with immediacy, the script runs perfect and the domain is attached, but "on demand", so the default lazy immediacy.

Thanks

**Comment by dnq** [comment]
Hi Andraesincostan,

If i run your code then i don't get an error. But still the deployment is set to 'on demand' inside the APIC.
Could you provide your complete test code?

Cheers
Richy

**Comment by dnq** [comment]
I think the issue itself is related to this part of the code (Line 990, acitoolkit.py)

```
if is_interfaces:
    # Only add the all-vlans physical domain if nobody has
    # attached any other domain
    if len(self.get_children(only_class=EPGDomain)) == 0:
        text = {'fvRsDomAtt': {'attributes': {'tDn': 'uni/phys-allvlans'}}}
        children.append(text)
    if self._dom_deployment_immediacy:
        text['fvRsDomAtt']['attributes']['instrImedcy'] = self._dom_deployment_immediacy
    if self._dom_resolution_immediacy:
        text['fvRsDomAtt']['attributes']['resImedcy'] = self._dom_resolution_immediacy
```
Is this check really required? I think there can be EPGs without Interfaces but with EPGDomains?
I would propose a fix like this:

EPGDomain.get_json()
```
def get_json(self):
    """
    Returns json representation of the fvTenant object

    :returns: A json dictionary of fvTenant
    """
    attr = self._generate_attributes()
    for relation in self._relations:
        if isinstance(relation.item, EPG):
            if relation.item._dom_deployment_immediacy:
                attr['instrImedcy'] = relation.item._dom_deployment_immediacy
            if relation.item._dom_resolution_immediacy:
                attr['resImedcy'] = relation.item._dom_resolution_immediacy
    return super(EPGDomain, self).get_json(self._get_apic_classes()[0],
                                           attributes=attr)
```

EPG.add_infradomain():
```
def add_infradomain(self, infradomain):
    """
    Add Infrastructure Domain to the EPG

    :param infradomain:  Instance of InfraDomain class.
    """
    if not isinstance(infradomain, EPGDomain):
        raise TypeError('add_infradomain not called with InfraDomain')
    self.populate_children(True)
    if self.has_child(infradomain):
        return
    self.add_child(infradomain)
    infradomain._add_relation(self)
```

**Comment by andraesincostan** [comment]
Hi Richy,
Thank you for your answer.
I have done the changes that you have suggested, still nothing has changed. I have the same error like initially.

```
  Traceback (most recent call last):
  File "create-complete-egp.py", line 85, in <module>
    resp = tenant.push_to_apic(session)
  File "/home/ubuntu-user/AciToolKit/acitoolkit/acitoolkit/acitoolkit.py", line 132, in push_to_apic
    self.get_json())
  File "/home/ubuntu-user/AciToolKit/acitoolkit/acitoolkit/acitoolkit.py", line 121, in get_json
    attributes=attr)
  File "/home/ubuntu-user/AciToolKit/acitoolkit/acitoolkit/acibaseobject.py", line 900, in get_json
    data = child.get_json()
  File "/home/ubuntu-user/AciToolKit/acitoolkit/acitoolkit/acitoolkit.py", line 330, in get_json
    attributes=attr)
  File "/home/ubuntu-user/AciToolKit/acitoolkit/acitoolkit/acibaseobject.py", line 900, in get_json
    data = child.get_json()
  File "/home/ubuntu-user/AciToolKit/acitoolkit/acitoolkit/acitoolkit.py", line 997, in get_json
    text['fvRsDomAtt']['attributes']['instrImedcy'] = self._dom_deployment_immediacy
KeyError: 'fvRsDomAtt'
```



Here is my code:
```python
from acitoolkit.acitoolkit import *
import json

# Get the APIC login credentials and login
description = 'acitoolkit simple epg creation application'
creds = Credentials('apic', description)
args = creds.get()
session = Session(args.url, args.login, args.password)
session.login()

#Function which checks if tenant exists otherwise creates the Tenant
def analyseTenant (tenant_in_params):
 tenant_list = Tenant.get(session)
  answer = 0
  for tenant in tenant_list:
     if tenant.name == tenant_in_params:
        print 'Tenant already in the APIC '
        answer = 1
        return tenant
  if answer == 0:
     tenant = Tenant(tenant_in_params)
     print 'New tenant has been created '
     return tenant


#open json file containing params
try:
   params = json.loads(open('params.json').read())
except (ValueError, KeyError, TypeError):
   print 'JSON format error '

#loop in the list
for i in params['epg']['list']:

   #Tenant
   tenant = analyseTenant(i['tenant'])
   print tenant.name

   #Create the Application Profile
   app = AppProfile(i['appProfile'], tenant)

   #Create the EPG
   epg = EPG(i['name'], app)

   #Create a Context, create a BridgeDomain, and link them together
   context = Context(i['context'], tenant)
   bd = BridgeDomain(i['bridgeDomain'], tenant)
   bd.add_context(context)

   #Place the EPG in the BD
   epg.add_bd(bd)

   #Get the Domain from the APIC and attach it to the EPG
   domain = EPGDomain.get_by_name(session, i['infra_domain'])
   print domain.name
   epg.add_infradomain(domain)
   epg.set_dom_deployment_immediacy('immediate')
   epg.set_dom_resolution_immediacy('immediate')
  
#Push the config to apic
resp = tenant.push_to_apic(session)


```

The script runs fine if I comment these 2 lines:
```  
 epg.set_dom_deployment_immediacy('immediate')
 epg.set_dom_resolution_immediacy('immediate')
```
Do you have another idea why these 2 functions are throwing this error? or how could I change the immediacy via the code?

**Comment by richardstrnad** [comment]
Hey Andraesincostan,

I had again a look into this, the problem arise that your EPGDomain hit's this part of the code:
```
if self._dom_deployment_immediacy:
    text['fvRsDomAtt']['attributes']['instrImedcy'] = self._dom_deployment_immediacy
if self._dom_resolution_immediacy:
    text['fvRsDomAtt']['attributes']['resImedcy'] = self._dom_resolution_immediacy
```

Strange is that my code never hits this part, it has to be related to your EPGDomain configs.
Could you provide me the following output:
```
session = Session('url', 'user', 'pw')
session.login()
for i in EPGDomain.get(session): print(i.get_interfaces())
```
My list are all empty, pretty sure that you got some infos in them.

Cheers
Richy

**Comment by andraesincostan** [comment]
Hi Richy,
My list is also empty. This is what I get:
```
[]
[]
[]
[]
[]
[]
[]
[]
```
Geers,
Andra

**Comment by richardstrnad** [comment]
Hi Andra,

Could you get in touch with me through the mail you can find on my profile?
We then update this Issue with our findings.

Cheers,
Richy

**Comment by aadishbahati** [comment]
I am facing same issue. Could you please guide what was the solution?
