### ISSUE TITLE
how to get contracts information from EPG

### ISSUE THREAD

**Issue by bluebluepc** [datacenter/acitoolkit#146]
Hi, i used epg.get_all_consumed() to get contracts in EPG. but it's null. 

and used epg.get_json() to get follwoing information:

{'fvAEPg': {'attributes': {'name': 'BD02EPG'}, 'children': []}}

code:

 tenants = aci.Tenant.get(session)

    for tenant in tenants:
        apps = aci.AppProfile.get(session, tenant)
        for app in apps:
            epgs = aci.EPG.get(session, app, tenant)
            for epg in epgs
                print str(epg.get_json())
                contracts =epg.get_all_consumed()

**Comment by richardstrnad** [comment]
Hi bluebluepc,

We had a similar issue #114. 
When you need the relations of the objects, you have to use .get_deep() on the Tenant.
I made you a short working code, hope this helps to get you in the right direction:
```
from acitoolkit.acitoolkit import *

session = Session('url', 'user', 'pw')
session.login()

tenants = Tenant.get_deep(session)

for tenant in tenants:
    apps = tenant.get_children(only_class=AppProfile)
    for app in apps:
        epgs = app.get_children()
        for epg in epgs:
            print(str(epg.get_json()))
            contracts = epg.get_all_consumed()
            for contract in contracts:
                print(contract.name)
```

**Comment by bluebluepc** [comment]
thanks,  well done. 
another question ? 

how to get it in EPG subscribe process ?

code like :
sys.stdout.write("Starting subscribe to apic epgs events")
    aci.EPG.subscribe(session)
    print(str(epg.get_json()))
            contracts = epg.get_all_consumed()
            for contract in contracts:
                print(contract.name)

**Comment by richardstrnad** [comment]
I think the EPG.subscribe is independent from the EPG Objects that exists.
This means, that you can use this code to subscribe:
```
aci.EPG.subscribe(session)
```

And you just have to grab the objects from the Tenant.get_deep() call, like this:
```
def getObject(obj_name):
    obj_search = Search()
    obj_search.name = obj_name
    return t.find(obj_search)[0]

session = Session('url', 'user', 'pw')
session.login()

t = Tenant.get_deep(session, names=('API_Test_Tenant',))[0]

epg = getObject('EPG_Sub')
print(epg.get_all_consumed())
```
Please be aware that the getObject function is really basic and could led to unintended side effects if there are multiple objects with the same name.

**Comment by richardstrnad** [comment]
@bluebluepc Can we close this issue or do you need further help regarding this topic?
