### ISSUE TITLE
diagram.py only shows first subnet on BD

### ISSUE THREAD

**Issue by ntmark** [datacenter/acitoolkit#150]
When running application/diagram.py the output diagram only includes the first subnet for each Bridge Domain in the dotted box coming off the BD.  
Also if there is more than one subnet it seems to only show the _first_created_ subnet and not the preferred one.

I've tried to find the problem but am only getting started in python.
Mark.

**Comment by kecorbin** [comment]
I'm not able to recreate.
![image](https://cloud.githubusercontent.com/assets/6739274/11534521/c53ae93a-98d4-11e5-9806-aa0c276e5ede.png)

**Comment by ntmark** [comment]
Thank you for looking at this, It is definitely happening for me, I've just pulled latest acitoolkit, and tried a few different configurations in ACI, with private subnet, and both subnets in BD being public, one subnet set to prefer, but no luck. 
We are running 1.1(3f), and python 2.7.5 on centos7.
I will keep trying to find out why, thank you for looking.
Mark.
![3-12-2015 8-52-56 a-m-](https://cloud.githubusercontent.com/assets/16088321/11542235/5717fa66-999b-11e5-86b4-32120c0c98c8.png)

**Comment by ntmark** [comment]
Have found issue, fvSubnet needs to have a unique 'name' value.
When creating a subnet through GUI, you're unable to set this, but via API it can be changed.
Now diagram.py draws with multiple subnets per BD.

**Comment by kecorbin** [comment]
That's really interesting..  I'll have to look into see how mine was working then..

**Comment by dyoshiha** [comment]
An MO location in the MIT tree is specified by a 'dn' attribute. The attribute must be a unique identifier, that is, two MOs must not have the same 'dn' value. Regarding to fvSubnet, the 'dn' is made by concatenating 'ip' attribute to the end of parent class's 'dn'. Example is as follows:

uni/tn-TENANT/BD-BRIDGEDOMAIN/subnet-[192.168.1.254/24]

So, you must not use the same 'ip' attribute to the different fvSubnet.

**Comment by ntmark** [comment]
Thanks, the IP attribute was different, 10.72.73.1/24 and 10.72.74.1/24, everything was different in the fvSubnet except for the name and scope attributes, where name="" and scope="public", descriptions/ip and all else was unique.
When I get back to work on Monday I'll update this with the whole BD +subtree config, as I am just as perplexed.

**Comment by cgascoig** [comment]
@ntmark you're correct - I can recreate this on the latest acitoolkit and latest APIC version when both subnets have the same (blank) "name" attribute (which is how they're created by the GUI).

This appears to be an issue in BaseACIObject. 

The two subnet objects get created with the same name attribute (which is ""):
```
DEBUG:root:Creating BridgeDomain bd1
DEBUG:root:Creating Subnet 
DEBUG:root:Creating Subnet 
```
The second Subnet will overwrite the first one when it's parent relationship is created:
```python
        if self._parent is not None:
            if self._parent.has_child(self):
                self._parent.remove_child(self)
```
because has_child uses an "==", which has been overridden to basically just check the `name` attribute:
```python
    def __eq__(self, other):
        if isinstance(other, self.__class__):
            self_key = (self.get_parent(), self.name)
            other_key = (other.get_parent(), other.name)
            return self_key == other_key
        return NotImplemented
```

Not sure the best way to fix this in BaseACIObject, but might be worth re-opening the issue so that options can be discussed?

**Comment by ntmark** [comment]
Reopend by request.
Thanks Chris.

Mark.

**Comment by cgascoig** [comment]
@ntmark #159 has now been merged which should fix this issue - can you pull the latest acitoolkit and test again?

Thanks,
Chris

**Comment by ntmark** [comment]
Pulled, and tested on newly created subnets.
Confirmed, this is now showing all subnets where name=""
Many thanks @cgascoig 

Mark.
