### ISSUE TITLE
aci-show-filter-entries.py has no output

### ISSUE THREAD

**Issue by toontuxop** [datacenter/acitoolkit#164]
hello, whi can help me with aci-show-filter-entries.py. it does not create any output.
i can print tenant and contract info, so that's working, but after "ACI.FilterEntry.get"
print shows no output at all.

or tnt in tenants:
    #print tenant
    contracts = ACI.Contract.get(session, tenant)
    for contract in contracts:
        #print contract,tenant
        filter_entries = ACI.FilterEntry.get(session, parent=contract, tenant=tenant)
        for fe in filter_entries:
            #print fe
            data.append({'filter_entry': fe.name,
                         'contract': fe.get_parent().name,
                         'tenant': fe.get_parent().get_parent().name})

i am quite a python newby, so any help is appreciated.

**Comment by richardstrnad** [comment]
Hey toontuxop,

The Contract/Filter model changed a bit, unfortunately the sample isn't updated yet. I will try to do that. But for now i can provide you the following example that does more or less the same.

```
import sys
import acitoolkit.acitoolkit as ACI

# Take login credentials from the command line if provided
# Otherwise, take them from your environment variables file ~/.profile
description = 'An application that logs on to the APIC and displays all of the Filter Entries.'
creds = ACI.Credentials('apic', description)
creds.add_argument('-e', '--filter_entry', help='The name of Filter Entry', default=None)
creds.add_argument('-c', '--contract', help='The name of contract', default=None)
creds.add_argument('-t', '--tenant', help='The name of tenant', default=None)
args = creds.get()

# Login to APIC
session = ACI.Session(args.url, args.login, args.password)
resp = session.login()
if not resp.ok:
    print('%% Could not login to APIC')
    sys.exit(0)

tenants = ACI.Tenant.get_deep(session)
for tenant in tenants:
    for tenant_child in tenant.get_children():
        if isinstance(tenant_child, ACI.Contract):
            print('- {}'.format(tenant_child.name))
            for contract_child in tenant_child.get_children():
                print('--- {}'.format(contract_child.name))
                for filter_child in contract_child.get_filters():
                    print('----- {}'.format(filter_child))
                    for filter_entry in filter_child.get_children():
                        print('------- {}'.format(filter_entry))
```

The hierarchy is like:
```
    +------------------+
    |                  |
    |      Tenant      |
    |                  |
    |                  |
    +-+--------------+-+
      |              |
      |              |
+-----+----+    +----+-----+
|          |    |          |
| Contract | +--+  Filter  |
|          | |  |          |
|          | |  |          |
+----+-----+ |  +----+-----+
     |       |       |
+----+-----+ |  +----+-----+
|          | |  |          |
| Contract | |  | Filter   |
| Subject  +-+  | Entry    |
|          |    |          |
+----------+    +----------+
```

Contract and Filter are both Childs of a Tenant, Contract has Contract Subjects and Filter has Filter Entries as their own Childs.
A Contract Subject has a relationship to Filters.

If anything is unclear, feel free to ask :-)

Cheers
Richy

**Comment by toontuxop** [comment]
Richy, thanks for this script. it works as you propably expected. sorry  for being a bit late with checking github, but did not had the the time to do so.

Regards,
Toon.

**Comment by richardstrnad** [comment]
Hi Toon,

Great to hear that.
Would be perfect if you could close the issue then.

Regards,
Richy
