### ISSUE TITLE
Contract get_scope() always returns 'context'

### ISSUE THREAD

**Issue by tigelane** [datacenter/acitoolkit#168]
When using the get_scope() method of the class Contract it only returns 'context' regardless of the true scope.   While looking at acitoolkit.py I seems that line 2528 is just hard coding this information rather than going and getting the real value.  Am I reading that correct?

**Comment by michsmit99** [comment]
Just committed a fix for this.
https://github.com/datacenter/acitoolkit/commit/7fdba56f95b72dbeac6f3ba9f3f58eba26755998

**Comment by tigelane** [comment]
Works great now.  Thanks for the update.

![screen shot 2016-02-29 at 5 00 11 pm](https://cloud.githubusercontent.com/assets/981666/13414244/edfbbad0-df05-11e5-92c0-686071a84bc7.png)
