### ISSUE TITLE
EPG name field is inconsistently populated

### ISSUE THREAD

**Issue by aidan-** [datacenter/acitoolkit#173]
When subscribing to EPG change events, the name field looks to be inconsistently populated.  During a _create_ event, the name field is populated as expected, but for _modifications_ and _deletes_ the field is 'None' (however, the dn field is populated as expected).  

It looks like the default _get_event_ function tries to handle this case ([acibaseobject.py, L440](https://github.com/datacenter/acitoolkit/blob/8ba08480cf149abd15a6a10cb3b045344d9b5569/acitoolkit/acibaseobject.py#L440)) but the name field is over written by the EPG function _populate_from_attributes_ ([acitoolkit.py, L927](https://github.com/datacenter/acitoolkit/blob/8ba08480cf149abd15a6a10cb3b045344d9b5569/acitoolkit/acitoolkit.py#L927)).

[Here is a very quick adaption](https://gist.github.com/aidan-/728eb1669e80ebac2ddd448f2a22493a) of _aci-subscribe-tenants.py_ to help illustrate the issue.  Run the script and modify or delete an EPG, the output looks like:
```
('EPG', 'None', 'has been deleted.')
```

I've got a very small patch that fixes this specific issue, but there may be other objects or attributes that are affected in similar circumstances.  For other fields it might not be too much of an issue, but I figured the name field is fairly mandatory (especially when the _dn_ field is populated). 

I'll make a PR shortly and reference this potential issue.

**Comment by michsmit99** [comment]
Thanks Aidan. Looking through the code, this occurs in a number of places and is due to the str() call on None.  In the case where dn is populated but name is not, we should be able to parse the name from the dn. I'll submit an additional fix for this.

**Comment by aidan-** [comment]
Nice, thanks for the quick response.  Just as an FYI, it looks like you may have accidentally committed some other changes in f77e692 by accident? (namely [_inheritance_apic_credentials.ini_](https://github.com/datacenter/acitoolkit/blob/f77e692ad794350a6939355824097b16044d33e4/applications/inheritance/inheritance_apic_credentials.ini))

**Comment by michsmit99** [comment]
Yes, Nice catch !  Backed out some of the changes in commit https://github.com/datacenter/acitoolkit/commit/eeeb04c63488686b8377934309bf8ed8ee20d4c9

**Comment by aidan-** [comment]
Cheers.

I've noticed another error in f77e692 when setting the _is_attribute_based field.  The value is potentially already a _bool_ type at that point and calling _.lower()_ on it causes an exception.  I have submitted PR #175 to potentially address this.
