### ISSUE TITLE
Certificate based authentication

### ISSUE THREAD

**Issue by ivar-lazzaro** [datacenter/acitoolkit#186]
First-Q-On-This-Project-Premise: Thanks for the fine job you guys do here. I am developing my homemade apic client but I'm planning to transition our code to acitoolkit instead (yay consistency!). I'm using github issues to ask questions because I've seen others here, but I'll be glad to use a different tool for that if any (internal Cisco ML?)

Question: Does acitoolkit support APIC's certificate based authentication, or is username/password the only supported way to connect to APIC when using this client? Is it in the roadmap/under dev?

**Comment by michsmit99** [comment]
Currently, it is username/password. I haven't seen many requests to add certificate based and I'm not aware of anyone actively adding it. I can certainly look into it if folks think it's valuable to have.

**Comment by ivar-lazzaro** [comment]
At the time when this issue was opened, certificate authentication was not yet implemented by the APIC Web Socket interface, and therefore it wasn't really meaningful to support it in acitoolkit.
As of Today, certificate authentication is supported for both HTTP and WS operations in APIC.

The most pressing use case behind this request is to address Telcos, that typically have policy restrictions about writing passwords in their config files (which is how Openstack connects to ACI when using password authentication on ACI).
