### ISSUE TITLE
Unable to use epg.get_all_consumed() or epg.get_all_provided() to get the contract information of a epg

### ISSUE THREAD

**Issue by nick00783** [datacenter/acitoolkit#214]
Hey guys:
    I find that I can't use get_all_consumed or get_all_provided to get the contract of EPG,it returns {} every time,do anyone know how to use it or is there any other way around to meet my need ?
Thanks for your helping..

**Comment by michsmit99** [comment]
The get_all_consumed and get_all_provided functions are meant to be called after the configuration has been created locally or pulled from the APIC using a call to Tenant class get_deep function.  How are you using them ?

Here's a small example of creating config locally:

    from acitoolkit import *
    tenant = Tenant('mytenant')
    app = AppProfile('myapp', tenant)
    epg = EPG('myepg', app)
    contract = Contract('mycontract', tenant)
    epg.provide(contract)
    print len(epg.get_all_provided())

**Comment by richardstrnad** [comment]
You can find a example with get_deep here:
https://github.com/datacenter/acitoolkit/issues/146

**Comment by nick00783** [comment]
thank you very much...looks like this is the solution
