### ISSUE TITLE
Configpush: more detailed input sanitization is needed

### ISSUE THREAD

**Issue by amney** [datacenter/acitoolkit#267]
Tetration policy can include a number of different attributes that are not compatible with ACI:
### Naming
These apply to Tenants, App Profiles, EPGs, VRFs, Contracts (and probably more)
- Spaces in names 
- Special characters in names (e.g. : or #)

To be more technical, the naming rules must satisfy these constraints:

> Naming Property -- [NAMING RULES]
Property Validators:
    Range:  min: "1"  max: "63"
        Allowed Chars:
            Regex: [a-zA-Z0-9_.-]+

When mangling names we should check the attribute conforms to these rules, and if not, try to sanitize them in some way.

### IP based EPGs
IP based EPGs cannot have a broadcast address as a classifier e.g. "255.255.255.255".

These should be stripped from the policy when enabling IP EPGs.

**Comment by amney** [comment]
@pvelumul would you be able to look into this? thanks!

**Comment by pvelumul** [comment]
code committed in #269

**Comment by amney** [comment]
Thanks @pvelumul
