### ISSUE TITLE
how to add description in tenant function

### ISSUE THREAD

**Issue by micruzz82** [datacenter/acitoolkit#270]
Hi Guys

Would you be able to help me out in regards to passing the description argument in the create tenant function as below.

# Create the Tenant
    tenant = aci.Tenant(args.tenant)

    # Push the tenant to the APIC
    resp = session.push_to_apic(tenant.get_url(),
                                tenant.get_json())
    if not resp.ok:
        print('%% Error: Could not push configuration to APIC')
        print(resp.text)

Wanted to use the same method of session.push_to_apic(tenant.get_url(), tenant.get_json())

Thanks Mike

**Comment by richardstrnad** [comment]
Hi Mike,

It's currently not possible to set the description 'directly' on the Tenant creation. But you can change the attribute of the object afterwards, it will get pushed to the APIC correctly.

Example
```
'''
This Scripts generate a new Tenant with a description
'''

from acitoolkit.acitoolkit import *

url = 'url'
user = 'user'
pw = 'pw'

session = Session(url, user, pw)
session.login()

tenant = Tenant('MyTenant')
tenant.descr = 'MyDescription'

tenant.push_to_apic(session)
```

Hope this helps.

Regards
Richy

**Comment by micruzz82** [comment]
That is perfectly fine Richard. I just didn't know the right way to send the argument. Many thanks for your help.
