### ISSUE TITLE
Error retrieving EPG attributes (bridge domains) again

### ISSUE THREAD

**Issue by Busesz** [datacenter/acitoolkit#288]
Hi there,
I know there was an issue, [https://github.com/datacenter/acitoolkit/issues/114](url) which is solved.
But, my problem is still exists. My .py file want to print all of the EPGs names which have relation to any BD, also want to print the BD name. 
First i go on the Tenants, i use the get_deep() merthod (as you suggested that in the issue #114 ),  then the AppProfiles, then the EPGs and then the BDs. When want to check that if epg.has_bd() always return false, so i can't get any value for my get_bd().

I insert into my code: 

#!/usr/bin/env python

import acitoolkit.acitoolkit as aci

def main():
    """
    Main show EPGs and BDs routine
    :return: None
    """
    description = ('***')
    creds = aci.Credentials('apic', description)
    args = creds.get()
    session = aci.Session(args.url, args.login, args.password)
    resp = session.login()
    if not resp.ok:
        print('Nem lehet bejelentkezni')
    
    tenant_names = []

    tenants = aci.Tenant.get_deep(session names=tenant_names)

    for tenant in tenants:
        apps = aci.AppProfile.get(session, tenant)
        for app in apps:
                epgs = aci.EPG.get(session, app, tenant)
                for e in epgs:
                        print e.name
                        print e.has_bd()
                        if e.has_bd():
                                print e.get_bd()
                                print '\n'

if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        pass

**Comment by pvelumul** [comment]
Hi,

We had a similar issue in #146 

When you need children along with relations from tenant, you need to use get_children instead of aci.AppProfile.get(session, tenant).

This is the working copy of code

#!/usr/bin/env python

import acitoolkit.acitoolkit as aci
from acitoolkit.acitoolkit import EPG, AppProfile

def main():
    """
    Main show EPGs and BDs routine
    :return: None
    """
    description = ('***')
    creds = aci.Credentials('apic', description)
    args = creds.get()
    session = aci.Session(args.url, args.login, args.password)
    resp = session.login()
    if not resp.ok:
        print('Nem lehet bejelentkezni')

    tenant_names = []

    tenants = aci.Tenant.get_deep(session,names=tenant_names)

    for tenant in tenants:
        apps = tenant.get_children(AppProfile)
        for app in apps:
            epgs = app.get_children(EPG)
            for e in epgs:
                print e.name
                print e.has_bd()
                if e.has_bd():
                    print e.get_bd()
                    print '\n'
if __name__ == '__main__':
        try:
            main()
        except KeyboardInterrupt:
            pass

**Comment by Busesz** [comment]
Wow! Thanks a lot for your fast answer!
You helped me out  with this problem!
Many thanks to you!
