### ISSUE TITLE
Contract, ContractSubject, Filter, FilterEntry

### ISSUE THREAD

**Issue by Busesz** [datacenter/acitoolkit#289]
Dear All,

!!First of all, this is not a bug, it's an important question!!

I read all of the sample codes, and started a search on the internet for any advice, but i dont find any answer yet. 
So I can create many separated filterentries with separated filter and empty contractsubjects, but i want these filterentries under one filter, then i want to create a relation between the filter and a contractsubject under a specific contract. Is there any solution how to do this with acitoolkit?

Best regards,
Balint

**Comment by Busesz** [comment]
Nvm, i made the solution.

**Comment by richardstrnad** [comment]
Hey @Busesz ,

I was a bit too slow :-)
Maybe you could post the solution for others?

Cheers
Richy

**Comment by Busesz** [comment]
Hi!

Ofc i can!
I called two existing EPGs. Then i create a Contract/or call an existing one, and also a ContractSubject, after that i create/call a Filter then i create many new FilterEntries.
This is my code:

Session = aci.Session(url, login, password)
Session.login()

tenant = aci.Tenant('Tenant_Name')
app1 = aci.AppProfile('AppProfile', tenant)
outside = aci.OutsideL3('OutsideRoutedNetwork', tenant)
EPGL3 = aci.OutsideEPG('OutsideEPG', outside)
EPGIN = aci.EPG('webepg', app1)
cont = aci.Contract('myContractName', tenant)
ContrSubj = aci.ContractSubject('myConSubjName',cont)
Filt =  aci.Filter('myFiltName',ContrSubj)
ContrSubj.add_child(Filt)

vz_entry = aci.FilterEntry(FilEname,
					parent=Filt,
					applyToFrag='no',
					arpOpc='unspecified',
					dFromPort='5672',
					dToPort='5685',
					etherT='ip',
					prot='tcp',
					sFromPort='80',
					sToPort='80',
					tcpRules='unspecified')


EPGL3.provide(cont)
EPGIN.consume(cont)
Session.push_to_apic(tenant.get_Url(), data=tenant.get_json())


This is my working solutinon, if you have any idea, how could i make it better, tell me please.
