### ISSUE TITLE
Can't get Filters/FilterEntries from unidirectional Contracts

### ISSUE THREAD

**Issue by danialre** [datacenter/acitoolkit#290]
When using get_all_filter_entries() on a Contract, or get_filters() on a ContractSubject, the returned list is empty if the ContractSubject has "Apply Both Directions" set to False (or is unchecked when creating it in the ACI web interface).

Replication steps:
1a. Create two Filters, "filter_SSH" and "filter_SMTP".

1b. Create two Contracts & Subjects in the web interface, SMTP and SSH - SMTP has "Apply Both Directions" and "Reverse Filter Ports" unchecked, but SSH has both checked. The SSH Subject has "filter_SSH" assigned, and the SMTP Subject has "filter_SMTP" assigned as either a Consumer-to-Provider or Provider-to-Consumer filter.

2. Retrieve the tenant with get_deep, and get Contract objects from the tenant:
```
>>> ten_deep = acitoolkit.Tenant.get_deep(session, names=("API_Test",))
>>> ssh_c = [c for c in ten_deep.get_children(acitoolkit.Contract) if 'SSH' in c.name][0]
>>> smtp_c = [c for c in ten_deep.get_children(acitoolkit.Contract) if 'SMTP' in c.name][0]
```

3. Get FilterEntries from each contract:
```
>>> ssh_c.get_all_filter_entries()
[<acitoolkit.acitoolkit.FilterEntry object at 0x108e1f550>]
>>> smtp_c.get_all_filter_entries()
[]
```

If this is the expected behavior for these ContractSubjects, is there a different way I can get a list of Filters associated to the ContractSubject/Contract?

Thanks!

**Comment by michsmit99** [comment]
I did some digging into this and it looks like the get_deep() call is getting the unidirectional filters but they are not gathered by the call to get_all_filter_entries(). I've added another parameter to the call to allow for gathering filters that are bidirectional only, input only, output only, or all directions.

**Comment by danialre** [comment]
This works great, thanks!
