### ISSUE TITLE
Associate VMM domain to EPG

### ISSUE THREAD

**Issue by arikgelman** [datacenter/acitoolkit#297]
Hi,

How do I associate VMM domain (already configured) to an EPG?

Thanks!

**Comment by richardstrnad** [comment]
Hi Arikgelman,

You can attach the VMM domain through the `attach` method, example below.

```python
from acitoolkit.acitoolkit import *

url = 'https://IP'
user = 'admin'
pw = 'pw'

session = Session(url, user, pw)
session.login()

vmm = VmmDomain.get_by_name(session, 'VMM_NAME')

tenant = Tenant('TENANT_NAME')
app = AppProfile('APP_NAME', tenant)
epg = EPG('EPG_NAME', app)

epg.attach(vmm)

x = tenant.push_to_apic(session)
print(x.text)
```

Regards
Richy

**Comment by arikgelman** [comment]
Thank you!! Didn't know about the get_by_name function.

**Comment by arikgelman** [comment]
@richardstrnad Hi,
The example you provide associate VMM domain to an EPG, But I was unable to find a way to set parameters like primary vlan, secondary vlan in the association?

Thanks

**Comment by jeandconte** [comment]
Anyone knows how to apply the same code using the option "Resolution: Immediate" ?

> Hi Arikgelman,
> 
> You can attach the VMM domain through the `attach` method, example below.
> 
> from acitoolkit.acitoolkit import *
> 
> url = 'https://IP'
> user = 'admin'
> pw = 'pw'
> 
> session = Session(url, user, pw)
> session.login()
> 
> vmm = VmmDomain.get_by_name(session, 'VMM_NAME')
> 
> tenant = Tenant('TENANT_NAME')
> app = AppProfile('APP_NAME', tenant)
> epg = EPG('EPG_NAME', app)
> 
> epg.attach(vmm)
> 
> x = tenant.push_to_apic(session)
> print(x.text)
> Regards Richy

**Comment by cpaggen** [comment]
> Anyone knows how to apply the same code using the option "Resolution: Immediate" ?
> 
> > Hi Arikgelman,
> > You can attach the VMM domain through the `attach` method, example below.
> > from acitoolkit.acitoolkit import *
> > url = 'https://IP'
> > user = 'admin'
> > pw = 'pw'
> > session = Session(url, user, pw)
> > session.login()
> > vmm = VmmDomain.get_by_name(session, 'VMM_NAME')
> > tenant = Tenant('TENANT_NAME')
> > app = AppProfile('APP_NAME', tenant)
> > epg = EPG('EPG_NAME', app)
> > epg.attach(vmm)
> > x = tenant.push_to_apic(session)
> > print(x.text)
> > Regards Richy

Looking at the [docs](https://acitoolkit.readthedocs.io/en/latest/acitoolkit.acitoolkit.html), I see _set_dom_resolution_immediacy(immediacy)_

**Comment by jeandconte** [comment]
I've already tested the "set_dom_resolution_immediacy", and it did not work as i expected, the config pushed to the apic still has the "immediate" by default. In fact what i need is to use the "pre provision", not the "immediate" value.

The docs mention the option "set_dom_resolution_immediacy" is applied only for PhysDom, it seems that for VMM the option doesn't exist.

**Comment by cpaggen** [comment]
There's no code for _preprovision_ -> look at lines 1317-1318 in [https://github.com/datacenter/acitoolkit/blob/master/acitoolkit/acitoolkit.py#L1317](https://github.com/datacenter/acitoolkit/blob/master/acitoolkit/acitoolkit.py#L1317)
```
        if immediacy not in ('immediate', 'lazy'):
            raise ValueError("Immediacy must be one of 'immediate' or 'lazy'")
```

The code seems to push _immediate_ for all VMM domains, see lines 1434-1437 of [https://github.com/datacenter/acitoolkit/blob/master/acitoolkit/acitoolkit.py#L1434C1-L1436C78](https://github.com/datacenter/acitoolkit/blob/master/acitoolkit/acitoolkit.py#L1434C1-L1436C78)
```
        for vmm in vmm_domains:
            text = {'fvRsDomAtt': {'attributes': {'tDn': vmm._get_path(),
                                                  'resImedcy': 'immediate'}}}
```

**Comment by jeandconte** [comment]
Thank you for your help.
