### ISSUE TITLE
install via pip

### ISSUE THREAD

**Issue by robphoenix** [datacenter/acitoolkit#301]
Will `acitoolkit` continue to be available via `pip`, rather than download & `python setup.py install`? The current version installed via `pip` is `0.3.1` and there has been a release since then and then over 700 commits since that. The [PyPI](https://pypi.python.org/pypi/acitoolkit/0.3.1) repository hasn't been updated since 2015-08-04, with no new release on GitHub since 2015 either.

When building tools that have `acitoolkit` as a dependency it would be great to be able to include an up-to-date release in the `requirements.txt` file. 

Would be good to know the intentions of the maintainers. More than happy to help out with this.

**Comment by michsmit99** [comment]
I just bumped the version to 0.4 and updated the package on PyPi. I think having the version regularly updated for requirements matching is a great idea. Any thoughts on how frequently versioning should occur e.g. wait for major code revisions or on a regular time scale ?

**Comment by Edsall** [comment]
Probably major code or feature changes.  What do you think?

**Comment by robphoenix** [comment]
Amazing! Thanks @michsmit99 
I agree with @Edsall, versioning on significant code changes, feature additions and important bug fixes is probably best, using semantic versioning.
It's perhaps also worth tagging the version and updating the releases page. 
You could automate some of this with a [Makefile](https://github.com/kennethreitz/requests/blob/master/Makefile#L49) perhaps?

**Comment by robphoenix** [comment]
closed by https://github.com/datacenter/acitoolkit/commit/18bfc6b7d2025c50bc96ed2bcf65a8f0074feb06
