### ISSUE TITLE
Associate VM or Phys Domain to EPG

### ISSUE THREAD

**Issue by kolbashj** [datacenter/acitoolkit#324]
How can I associate a VM or Phys domain to an end point group?  Does the toolkit provide a method to accomplish this?

**Comment by kolbashj** [comment]
searched a little more and found the following resoultuon:

https://github.com/datacenter/acitoolkit/issues/297

**Comment by arikgelman** [comment]
Hi,
The example in the issue does provide the way to associate VMM domain to an EPG, but have you able to find a way to set parameters like primary vlan, secondary vlan in the association?

Thanks
