### ISSUE TITLE
aci-show-endpoints.py missing brackets in line 70

### ISSUE THREAD

**Issue by christung16** [datacenter/acitoolkit#336]
Original, it shows error in pycharm:
# Display the data downloaded
    print tabulate(data, headers=["MACADDRESS", "IPADDRESS", "INTERFACE",
                                  "ENCAP", "TENANT", "APP PROFILE", "EPG"])

modified:
# Display the data downloaded
    print (tabulate(data, headers=["MACADDRESS", "IPADDRESS", "INTERFACE",
                                  "ENCAP", "TENANT", "APP PROFILE", "EPG"]))

**Comment by michsmit99** [comment]
Fixed with commit e286197227122af2fcbc088659ecebdf1d0b5422
