### ISSUE TITLE
Wrong domain_name returned when using EPGDomain.get()

### ISSUE THREAD

**Issue by yazshen** [datacenter/acitoolkit#342]
Hi ACI Team,

When I used EPGDomain.get() to list domain information in EPG, I found domain name wasn't correct:

pip3 search acitoolkit
acitoolkit (0.4)  - This library allows basic Cisco ACI APIC configuration.
  INSTALLED: 0.4 (latest)

Source Code:
    import acitoolkit.acitoolkit as aci
    objdomains = aci.EPGDomain.get(session)
    for objdomain in objdomains:
        print("DN is ", objdomain.dn, " EPGDomain is " , objdomain.domain_name)

Returned:

DN is  uni/tn-yazshen01/ap-ANP01/epg-192.168.101.x/rsdomAtt-[uni/phys-yazshen-PD01]  EPGDomain is  yazshen

The correct domain name should be "yazshen-PD01", but "yazshen" returned.

Thanks.

**Comment by aymanovitchy** [comment]
try change the - with _ and do the same
