### ISSUE TITLE
ValueError: Subnet address is not set

### ISSUE THREAD

**Issue by igoqueen5** [datacenter/acitoolkit#346]
Hi, thanks for opening this issue.

I'm trying to create subnet inside BridgeDomain but 'ValueError: Subnet address is not set' is keeps outputed.

Here is my source code below.
```
for t in tenant_list:
    tenant = Tenant(t)
  
    for app_pro in appprofile_list: 
      app = AppProfile(app_pro, tenant)
    
    for e in epg_list:
      epg = EPG(e, app)
  
    for v in vrf_list:
      context = Context(v, tenant)

    for bd in bridgedomain_list:
      bridgedomain = BridgeDomain(bd, tenant)
    
    for sub in network_list:
      subnet = Subnet(sub, bridgedomain)
      # print subnet =>1.1.1.1/24, 2.1.1.1/24 (and so on...)
    
    bridgedomain.add_context(context)
  
    epg.add_bd(bridgedomain)
    bridgedomain.add_subnet(subnet)
```

When I print subnet it shows me subnet for example 1.1.1.1/24 .
So I think the error message "ValueError: Subnet address is not set" is something weird because
it is NOT None Type. (I have read acitoolkit.py )

Any ideas?

Thanks.

P.s.
I'm non native English speaker so I'm sorry for if something difficult to read this issue.

**Comment by michsmit99** [comment]
Subnet requires the ip attribute to be set in addition to the name (although many use the ip address as the name as well).

It should work, if you add the following line after `subnet = Subnet(sub, bridgedomain)` :
`subnet.ip = sub`

**Comment by igoqueen5** [comment]
It works! Thanks for your help!
