### ISSUE TITLE
The IP address for side A/B  of the SVI interface under Logical Interface Profile

### ISSUE THREAD

**Issue by psaneem** [datacenter/acitoolkit#347]
Is there a method in the toolkit that allows me to pass the side A and Side B ip addresses for the SVI , i only see l3if.set_addr('x.x.x.x/y') which sets one IP for the SVI ..

**Comment by MTWiley** [comment]
I might be wrong, but I think it's handled a little differently on ACI and there isn't an A/B + HSRP address. It should just be the gateway address.

**Comment by psaneem** [comment]
thanks for the reply @MTWiley , let me ask it in a different way, with the acitoolkit is there a difference between a normal port channel and a Virtual port channel because for the latter then we will need a Side A/B for the SVI

**Comment by MTWiley** [comment]
My understanding is that a VPC would aggregate links from across multiple leafs vs a port channel which would only aggregate links on a single leaf.
