### ISSUE TITLE
acilint not running

### ISSUE THREAD

**Issue by russStarr** [datacenter/acitoolkit#42]
I am wanting to play around with acilint but I can't get it working. I've tried in both my Linux and Mac OS environments. I get the following output:

> $ python acilint.py
 Getting configuration from APIC....
Traceback (most recent call last):
  File "acilint.py", line 334, in <module>
    checker = Checker(session)
  File "acilint.py", line 29, in __init__
    self.tenants = Tenant.get_deep(session)
  File "build/bdist.macosx-10.5-x86_64/egg/acitoolkit/acitoolkit.py", line 120, in get_deep
  File "build/bdist.macosx-10.5-x86_64/egg/acitoolkit/acibaseobject.py", line 279, in get_deep
  File "build/bdist.macosx-10.5-x86_64/egg/acitoolkit/acibaseobject.py", line 279, in get_deep
  File "build/bdist.macosx-10.5-x86_64/egg/acitoolkit/acibaseobject.py", line 271, in get_deep
AttributeError: type object 'Subnet' has no attribute '_get_toolkit_to_apic_classmap'

I have verified my credentials are valid and have tried variations of credential inputs (cli, env variable, credentials.py). 

My toolkit was last updated today.

> $ git pull dc master
From https://github.com/datacenter/acitoolkit
 * branch            master     -> FETCH_HEAD
Updating 227a7cc..a8afccc
Fast-forward
 acitoolkit/acitoolkit.py          | 207 +++++++++++++++++++++++++++++++++++++------------------------------------
 acitoolkit/acitoolkitlib.py       |  71 ++++++++++++++++++-------
 applications/cli/acitoolkitcli.py |  12 ++++-
 tests/aciphysobject_test.py       |  45 +++++++++++-----
 tests/acitoolkit_test.py          | 250 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-------
 tests/acitoolkitlib_test.py       |  63 +++++++++++++++++++++++
 6 files changed, 496 insertions(+), 152 deletions(-)
 create mode 100644 tests/acitoolkitlib_test.py

My fabric is on 1.0.3f. Any ideas before I trip over my feet looking at the code?

Other potentially useful information:

> $ python -V
Python 2.7.6 :: Anaconda 1.9.2 (x86_64)
$ pip list | grep aci
acicobra (1.0-3f)
acicobrasdk (1.0-2m)
acimodel (1.0-3f)
acitoolkit (0.1)

**Comment by michsmit99** [comment]
I wasn't able to reproduce your problem in any of my setups but I did check in a fix that should address the problem being seen.  Please give it a try by pulling the latest.

Also, it looks like you are running an installed version which means you need to re-run 'python setup.py install' after updating.  To avoid this, you can install using 'python setup.py develop' and that will link the local toolkit files so when you git pull, you will always be running the latest.

**Comment by russStarr** [comment]
Thank you @michsmit99. I pulled the latest and it works.
