### ISSUE TITLE
escaping complex passwords

### ISSUE THREAD

**Issue by kennega** [datacenter/acitoolkit#52]
First contribution here so please be kind - I am using two controllers, one in San Diego and one in New York City. My SD controller has a "normal" admin password, whereas my NYC controller has a password with a special character (an exclamation) - if I connect using say, the snapback tool, I can create a snap fine in SD. However when I try to create a snap in NYC, it bombs. Here's an example on the command line:
NYC:
KEGARREA-M-G0EU:lint kegarrea$ python acilint.py -l admin -p Ins!3579 -u https://10.87.34.16
-bash: !3579: event not found

SD:
KEGARREA-M-G0EU:lint kegarrea$ python acilint.py -l admin -p Cisco321 -u https://10.95.33.232
Getting configuration from APIC....
Processing configuration....
Critical 001: EPG 'default' in tenant 'infra' app 'access' is not assigned security clearance
etc etc

Hopefully this is a bug and not user error.

**Comment by dainman** [comment]
Try enclosing password in single quote

Sent from my iPhone

On Apr 7, 2015, at 6:30 PM, kennega <notifications@github.com<mailto:notifications@github.com>> wrote:


First contribution here so please be kind - I am using two controllers, one in San Diego and one in New York City. My SD controller has a "normal" admin password, whereas my NYC controller has a password with a special character (an exclamation) - if I connect using say, the snapback tool, I can create a snap fine in SD. However when I try to create a snap in NYC, it bombs. Here's an example on the command line:
NYC:
KEGARREA-M-G0EU:lint kegarrea$ python acilint.py -l admin -p Ins!3579 -u https://10.87.34.16
-bash: !3579: event not found

SD:
KEGARREA-M-G0EU:lint kegarrea$ python acilint.py -l admin -p Cisco321 -u https://10.95.33.232
Getting configuration from APIC....
Processing configuration....
Critical 001: EPG 'default' in tenant 'infra' app 'access' is not assigned security clearance
etc etc

Hopefully this is a bug and not user error.

**Comment by kennega** [comment]
Have tried that as well as double quotes and backtick... and trying to escape it with \! - no luck on any of them.

**Comment by michsmit99** [comment]
Your original issue is bash interpretation of the ! character.  I tried with the single quotes 
python acilint.py -l admin -p 'Ins!3579' -u https://10.87.34.16 
and it "worked" (meaning that the password was accepted) but fails on your APIC due to the following issue:
https://communities.cisco.com/message/171497

**Comment by kennega** [comment]
Confirmed - thanks. I enabled TLSv1 and everything worked as expected. Thanks for the help!
