### ISSUE TITLE
aci-show-interfaces-stats

### ISSUE THREAD

**Issue by jgmitter** [datacenter/acitoolkit#55]
for interface in sorted(interfaces, key=lamdba x: x.if_name):

Library/Frameworks/Python.framework/Versions/2.7/bin/python2.7 /Users/jgmitter/Downloads/ACIDemo/DemoFolder/acitoolkit/samples/aci-show-interface-stats.py
  File "/Users/jgmitter/Downloads/ACIDemo/DemoFolder/acitoolkit/samples/aci-show-interface-stats.py", line 74
    for interface in sorted(interfaces, key=lamdba x: x.if_name):
                                                   ^
SyntaxError: invalid syntax

Process finished with exit code 1

**Comment by michsmit99** [comment]
Typo slipped in.  Checked in a fix. Please try the latest.

**Comment by jgmitter** [comment]
Thanks!


        Jason Gmitter, CCIE 12030
Cisco: Nexus/ACI Technical Solutions Architect
[cid:28D39E35-9EB4-444B-AC80-E608D6773159]  +1.408.894.<tel:+1.408.894.7683>7683<tel:+1.408.894.7683>
[cid:2F1EFA1F-6EC2-481C-8AE5-CD3E7DF4B6F0]  jgmitter@cisco.com<mailto:jgmitter@cisco.com>
[cid:1DE36242-5C5E-476A-A3B5-CED497E59EA1]  jgmitter@cisco.com<xmpp:jgmitter@cisco.com>
 [cid:DEA109E4-819D-4715-9D04-C1C024756530]  JabberCall Me<https://sjc-jabberc-ext.cisco.com/call/88947684@cisco.com?name=Jason%20Gmitter> browser-based video chat.

**Comment by tjle** [comment]
Jason, I just watch your video on YouTube. What Python editor was you using in that video? It can edit the code, run and CLI on it as well. Thanks!
