### ISSUE TITLE
ACI toolkit versioning and tags

### ISSUE THREAD

**Issue by jonstacks13** [datacenter/acitoolkit#66]
Hi,

I was wondering if it would be possible to start updating the version of this package to make identifying old installations possible. It would also be nice if releases were tagged so that a user could install a particular version of the package in case future improvements are not backwards compatible.

[Python Version Scheme](https://www.python.org/dev/peps/pep-0440/#version-scheme)

Thanks for your consideration.

**Comment by jonstacks13** [comment]
Hi, is there any update on this?

**Comment by aburnsdimensiondata** [comment]
It would be handy to have this on some of my company's projects, as well.

**Comment by michsmit99** [comment]
I think this makes a lot of sense and have been looking at the best way to do this. We should be able to add this very shortly.

**Comment by michsmit99** [comment]
I bumped the version to 0.2 and tagged the release.  I also added support to read the version from within your code e.g. 
`>>> from acitoolkit import __version__`
`>>> print __version__`
`0.2`
`>>>`

**Comment by aburnsdimensiondata** [comment]
Sweet, thanks @michsmit99. This meets all the needs on my end, so from my point of view this issue is ready to close.

**Comment by jonstacks13** [comment]
@michsmit99, what is the plan for versioning? Will all future dot releases be guaranteed to be passive and not break any existing functionality; with the understanding that if functionality is changed, it will be a new major release?

**Comment by michsmit99** [comment]
@jonstacks13, I was thinking that we would follow that philosophy. In general, we have been trying to maintain backwards compatibility wherever possible. That said, guarantee is a strong word and we are currently at 0.2. Generally pre-1.0 releases mean that things can change.  If folks feel we should be at 1.0, we can move to a major release.  My thought is that a lot of areas in the core of the toolkit have not changed in quite some time and look pretty solid with high test coverage, but there are some areas that could use the protection of a pre-1.0 release.  I'd love to hear other's thoughts on the topic.

**Comment by jonstacks13** [comment]
@michsmit99, that sounds great to me! I will close this issue since this meets my needs.
